### ISSUE TITLE
[suggestion if possible] a way to modify TaN canteen capacity

### ISSUE THREAD

**Issue by Biviho** [ikexing-cn/RandomTweaker#29]
i saw your mod and it's really interesting in the feature it proposes, so i was wondering, since you are making methods for Tan, if it's possible to add a function to modify Tan canteen capacity, since it's not something provided by Tan

**Comment by ikexing-cn** [comment]
of course, but it will take some time, because in the meantime I'm taking my driving test.

**Comment by ikexing-cn** [comment]
hmm, I'm afraid I have to say sorry.
I misunderstood the description of the problem because I didn't play the `TAN` Mod in an English game before ...... After I confirmed it, I found out that this feature not be possible or said easy to implement, especially by the way `CrT` provides the `Mothod`.
In terms of technical details, this is an Item, so a lot of modifications are written dead internally, and I need a lot of `Mixin` if I want to make changes to it, which will take a long time to consume, so I can only say sorry.
